name: Build and Test Angular Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run Angular build command
        uses: ./.github/actions/angular-action
        with:
          node_version: '16'
          angular_command: 'build'
          project_directory: './angular-app'

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: ./angular-app/dist
