name: Use Custom GitHub Action

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Use the custom action (from a local directory within the same repository)
      - name: Run My Custom Action
        uses: ./ .github/actions/my-action  # Use relative path for local action
        with:
          name: 'Pritam'  # Custom input for the action
